mlflow:
  AWS_ACCESS_KEY_ID: ****
  AWS_SECRET_ACCESS_KEY: ****
  MLFLOW_S3_ENDPOINT_URL: http://192.168.180.***:9000
  MLFLOW_TRACKING_URI: http://192.168.180.***:5000

api_youtube:
  YOUTUBE_API_KEY: **************************************




